### ISSUE TITLE
PCにてメニューのEnglishをクリックすると下層ページのメニューが切れる

### ISSUE THREAD

**Issue by nukaga** [wcosaka2018/wcosaka2018-theme#14]
![2018-03-25 19 07 50](https://user-images.githubusercontent.com/3480985/37873890-034f1eb0-3060-11e8-8df1-485a9f78204c.png)
Code of Cond で右端切れております。

**Comment by nukaga** [comment]
Mac OS Sirrea / Google Chrome

**Comment by gouten5010** [comment]
最後の要素だけpositionを変更します。

**Comment by gouten5010** [comment]
@nukaga 本番反映しているので、確認後問題なければCloseしてください

**Comment by nukaga** [comment]
完璧です。
![2018-03-26 9 20 25](https://user-images.githubusercontent.com/3480985/37881734-fc1d62d8-30d6-11e8-971c-3879df703419.png)
Closeします。
