### ISSUE TITLE
メニューの参加登録項目

### ISSUE THREAD

**Issue by gouten5010** [wcosaka2018/wcosaka2018-theme#5]
を、一番右に寄せて、目立つ色に変えるか枠線つけてほしいです。

### image
| HOME | メニュー | メニュー | メニュー | <-----SPACE----> | 参加登録 |

**Comment by gouten5010** [comment]
```
.menu {
            display: flex !important;
            justify-content: flex-start;
}
```
```
.join {
            margin-left: auto;
}
```

**Comment by marie-tomoishi** [comment]
その場合、ソーシャルリンクはどこにしましょうか？フッターですか？

**Comment by gouten5010** [comment]
ソーシャルリンクをワイヤーフレームの形にするのが可能であれば、この課題は閉じても大丈夫です。
この課題どおりに実装する場合は、フッターの、WordPressのロゴの上ですね。
