### ISSUE TITLE
投稿記事の整形

### ISSUE THREAD

**Issue by gouten5010** [wcosaka2018/wcosaka2018-theme#8]
https://gist.github.com/gouten5010/498018463cceb32edc1cd20621076672

↑を記事に入れて、整形する

**Comment by marie-tomoishi** [comment]
新規投稿に入れて、css組んでくってことであってますか？
_post-format.scssですよね？

**Comment by gouten5010** [comment]
@marie-tomoishi 合ってます。
`.entry-content`の中に書く形でやっていただければ他に影響は出ないかと思います。

**Comment by gouten5010** [comment]
@marie-tomoishi 基本的なところはこれで、あとはおいおい、いい感じにまた整形しましょう。
